### PR TITLE
Update to point to DispatcherQueueTimer API.

### PR DESCRIPTION
**Pull request by jeffstall**

### CODE REVIEW

**Comment by mikematteson** [comment]
@msatranjr  : PR passes acceptance checklist **EXCEPT** for one blocking issue: 

- Requirement: *Links to pages that do not require a locale code to render must be coded as locale-agnostic (that is, they must not contain "/en-us" in the URL).* 
  **Please remove unnecessary "/en-us" term from URL before merging.**

After this issue is fixed, please evaluate further as needed and merge if appropriate.

**Comment by jeffstall** [comment]
The en-us pattern is the same as other links on this page. I'd prefer local consistency, since I don't know what the clear alternative is.

**Comment by mikematteson** [comment]
@jeffstall : Point taken about consistency. By our content requirements, *none* of the docs.microsoft.com URLs on the page should have the /en-us term, but our PR review policy is to limit requests for fixes to the scope of the PR as submitted. So...

@msatranjr : Can you remove the locale specifier from all docs.microsoft.com URLs in the file as an additional commit here before you merge? Alternatively, just merge as submitted by Jeffrey and then pinky-swear to fix these in VSTS? 😃  Your call.

**Comment by jeffstall** [comment]
You're making my life too hard.

**Pull request closed without merging**
