### PR TITLE
Minor typo fix

### PR DESCRIPTION
**Pull request by Zopolis4**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Zopolis4 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@drewbatgit - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger20** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Review by drewbatgit — APPROVED** [review]

**Comment by drewbatgit** [comment]
#sign-off

**Pull request merged**
