### PR TITLE
WinUI 3 Release Notes: more info on INotifyPropertyChanged/INotifyCollectionChanged

### PR DESCRIPTION
**Pull request by kmahone**
Follow up to https://github.com/MicrosoftDocs/winrt-related/pull/154 to address PR feedback.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@kmahone : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jebishop

**Comment by kmahone** [comment]
@ranjeshj @MikeHillberg this PR addresses the comments from #154 that were added after the PR had already merged.

**Comment by PRMerger20** [comment]
@kmahone : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jebishop

**Review by ranjeshj — APPROVED** [review]

**Comment by PRMerger9** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jebishop

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Review by MikeHillberg — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
